### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by ilya-shikhaleev** [jho4us/tc#2]
test.TID - буква Т лишняя в названии типа. test.ID подходит больше, чем test.TID.

**Comment by ilya-shikhaleev** [comment]
test.TestCore - слово Core вызывает вопросы. Можно TestNew, TestConstruction, TestNewTestCreation

**Comment by ilya-shikhaleev** [comment]
testRepository.Accessor - зачем поле экспортируемое? Его использования вне пакета repo нет.

**Comment by ilya-shikhaleev** [comment]
```go
func NewTestRepository(path string) (test.Repository, error) {
	db, err := dbconf.DBFromConfig(path)
```

Лучше инъектить объект доступа к базе снаружи, поскольку конфигурирование его может усложниться. В данный момент функция NewTestRepository выполняет больше одной задачи.

**Comment by ilya-shikhaleev** [comment]
Healthz проба по примеру из документации ожидает тело ответа "ok", а не только заголовок. Но нигде не написано, что это обязательно. См. https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/
Предлагаю добавить и тело ответа.

**Comment by ilya-shikhaleev** [comment]
Если бы в задании было требование, что два теста не могут иметь одинаковых имён, где бы вы это реализовали?

**Comment by ilya-shikhaleev** [comment]
tc/tc/transport.go:58
Константы "POST" и остальные нужно заменить на http.MethodPost.

**Comment by ilya-shikhaleev** [comment]
Название пакета tc не отражает содержимое пакета. Тут лучше подошло бы editing. И сразу можно разделить чтение и запись, тогда методы на получение списка тестов и прочие операции чтения лежали бы в пакете reading.
Заодно отмечу, что метод tc.Service.Tests правильнее назвать ListTests, GetTests или GetTestList (нужен глагол)

**Comment by jho4us** [comment]
> Если бы в задании было требование, что два теста не могут иметь одинаковых имён, где бы вы это реализовали?

Unique constraint в DDL плюс правильная реакция в frontend предлагающая исправить имя

**Comment by jho4us** [comment]
> Название пакета tc не отражает содержимое пакета. Тут лучше подошло бы editing. И сразу можно разделить чтение и запись, тогда методы на получение списка тестов и прочие операции чтения лежали бы в пакете 
Тут всего лишь следование языку задания - а оно называется test constructor, а не test editor :)
> Заодно отмечу, что метод tc.Service.Tests правильнее назвать ListTests, GetTests или GetTestList (нужен глагол)

хм, там нет такого метода - есть TestService - и он и есть глагол

**Comment by jho4us** [comment]
> test.TestCore - слово Core вызывает вопросы. Можно TestNew, TestConstruction, TestNewTestCreation

Не думаю что существенно

**Comment by jho4us** [comment]
> Healthz проба по примеру из документации ожидает тело ответа "ok", а не только заголовок. Но нигде не написано, что это обязательно. См. https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/
> Предлагаю добавить и тело ответа.

Тут да, пропустил - при первом же деплое исправил бы. В тесте про kubernetes вообще ни слова нет ;)

**Comment by jho4us** [comment]
> test.TID - буква Т лишняя в названии типа. test.ID подходит больше, чем test.TID.

fixed

**Comment by jho4us** [comment]
> test.TestCore - слово Core вызывает вопросы. Можно TestNew, TestConstruction, TestNewTestCreation

fixed

**Comment by jho4us** [comment]
> testRepository.Accessor - зачем поле экспортируемое? Его использования вне пакета repo нет.

fixed

**Comment by jho4us** [comment]
> Healthz проба по примеру из документации ожидает тело ответа "ok", а не только заголовок. Но нигде не написано, что это обязательно. См. https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/
> Предлагаю добавить и тело ответа.

fixed

**Comment by jho4us** [comment]
> tc/tc/transport.go:58
> Константы "POST" и остальные нужно заменить на http.MethodPost.

fixed

**Comment by ilya-shikhaleev** [comment]
> хм, там нет такого метода - есть TestService - и он и есть глагол

```go
type Service interface {
	// CreateTest registers a new empty test in the system
	CreateTest(name string) (test.ID, error)

	// LoadTest returns a read model of a test.
	LoadTest(id test.ID) (Test, error)

	// PutTest update test contents
	PutTest(t *Test) error

	// DeleteTest delete test from a system.
	DeleteTest(id test.ID) error

	// Tests returns a list of all tests in a system.
	Tests() []Test
}
```
Речь шла про последний метод этого интерфейса
